name: icmc
dependencies:
  - python==3.9.7
  - pip
  - git
  - conda-forge::cxx-compiler
  - conda-forge::m2w64-toolchain
  - conda-forge::libpython
  - blas
  - mkl-service
  - seaborn
  - matplotlib
# conda install nb_conda_kernels -n base
# conda env create -f environment.yml
# conda activate icmc
# pip install git+https://github.com/mwong009/pycmtensor.git@develop -U
