name: icmc_comp
channels:
  - conda-forge
  - defaults
dependencies:
  - blas>=1.0
  - pip>=21.2.4
  - python>=3.9.7
  - pytest>=6.2.5
  - numpy>=1.21.5
  - git>=2.34.1
  - cxx-compiler>=1.3.0
  - m2w64-toolchain>=5.3.0
  - mkl-service>=2.4.0
  - ipykernel>=6.4.1
  - ipython>=7.31.1
  - libblas>=3.9.0
  - libpython>=2.1
  - pip:
    - aesara==2.4.0
    - biogeme==3.2.8
    - dill==0.3.4
    - pandas==1.4.1
    - pycmtensor==0.1.0
    - pytz==2021.3
    - scipy==1.7.3
    - tqdm==4.62.3