name: icmc
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.7
  - pip>=21.2.4
  - git>=2.34.1
  - cxx-compiler==1.3.0
  - m2w64-toolchain==5.3.0
  - libblas>=3.9.0
  - libpython>=2.1
  - ipykernel>=6.9.1
  - ipywidgets>=7.6.5
  - pydot>=1.4.2
  - mkl-service>=2.4.0
# conda install nb_conda_kernels
# conda env create -f environment.yml
# conda activate pycmtensor-dev
# pip install . , or
# pip install git+https://github.com/mwong009/pycmtensor.git
# conda remove --name icmc-temp --all
